<a href="https://colab.research.google.com/github/SarthakData2026/AI_IN_DATA_SCIENCE/blob/main/m2_ch1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##chapter1
##data manipulation with pandas

##1.series

##panda library:
-open source for data manipulation , analysis
##use:
data cleaning , EDA , feature engineering,
easy work with csv,json,sql

##operation in series :
sum,min,max

#vectorized operation:
+,-,*,%

In [ ]:
import pandas as pd

In [ ]:

import pandas as pd
marks=[2,4,6,8,10]
ds=pd.Series(marks)
print(ds)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
#custoimize index
marks=[2,4,6,8,10]

ds=pd.Series(marks,index=('a','b','c','d',"e"))#number of index=number of elements
print(type(ds))
print(ds)

<class 'pandas.core.series.Series'>
a     2
b     4
c     6
d     8
e    10
dtype: int64

In [ ]:
#custoimize index
marks=[2,4,6,8,10]

ds=pd.Series(marks,index=('a','b','c','d',"e"))#number of index=number of elements
print(type(ds))
print(ds)

<class 'pandas.core.series.Series'>
a     2
b     4
c     6
d     8
e    10
dtype: int64

In [ ]:
#custoimize index
marks=[2,4,6,8,10]

ds=pd.Series(marks,index=('a','b','c','d',"e"),dtype=float,name="marksheet")#number of index=number of elements
print(type(ds))
print(ds)

<class 'pandas.core.series.Series'>
a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
Name: marksheet, dtype: float64

#1.1  common operation

In [ ]:
print(f"sum is {ds.sum()}")

sum is 30.0

In [ ]:
print(ds.min())

2.0

In [ ]:
print(ds.max())

10.0

In [ ]:
print(ds.mean())

6.0

##1.2 indexing and slicing

In [ ]:
print(f"access element by integer nuymber {ds[2]}")

access element by integer nuymber 6.0

/tmp/ipykernel_842/863189245.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(f"access element by integer nuymber {ds[2]}")

In [ ]:
print(f"access element by  variable  {ds["b"]}")

access element by  variable  4.0

In [ ]:
print(f"slicing in series \n{ds[0:4]}")

slicing in series
a    2.0
b    4.0
c    6.0
d    8.0
Name: marksheet, dtype: float64

##1.3 vectorization func

In [ ]:
ds*3

a     6.0
b    12.0
c    18.0
d    24.0
e    30.0
Name: marksheet, dtype: float64

In [ ]:
ds**3

a       8.0
b      64.0
c     216.0
d     512.0
e    1000.0
Name: marksheet, dtype: float64

In [ ]:
ds%4

a    2.0
b    0.0
c    2.0
d    0.0
e    2.0
Name: marksheet, dtype: float64

In [ ]:
ds-9

a   -7.0
b   -5.0
c   -3.0
d   -1.0
e    1.0
Name: marksheet, dtype: float64

In [ ]:
info={
    "name":"sarthak",
    "age":21
}
(pd.Series(info))

name    sarthak
age          21
dtype: object

#cerate series by single number

In [ ]:
num=pd.Series(5)
print(num)

0    5
dtype: int64

In [ ]:
num=pd.Series(5,index=[1,2,3,4,5])
print(num)

1    5
2    5
3    5
4    5
5    5
dtype: int64

In [ ]:
num1=pd.Series(5,index=[1,2,3,4,5])
num2=pd.Series(10,index=[1,2,3,4,5])
print(num1,num2)

1    5
2    5
3    5
4    5
5    5
dtype: int64 1    10
2    10
3    10
4    10
5    10
dtype: int64

In [ ]:
num1=pd.Series(5,index=[1,2,3,4,5])
num2=pd.Series(10,index=[10,20,30,40,50])
print(num1+num2)

1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
10   NaN
20   NaN
30   NaN
40   NaN
50   NaN
dtype: float64

In [ ]:
num1=pd.Series(5,index=[1,2,3,4,5])
num2=pd.Series(10,index=['a','b','c','d','e'])
print(num1+num2)

1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

#2.1 dataframe

In [ ]:
import pandas as pd

In [ ]:
students={'names':['sarthak','rahul','dev','pragya','varun'],
          'roll_num':[100,200,300,400,500],
          'marks':[20,30,40,50,60]}
df=pd.DataFrame(students)
df.index.name='indx'
print(df)

        names  roll_num  marks
indx
0     sarthak       100     20
1       rahul       200     30
2         dev       300     40
3      pragya       400     50
4       varun       500     60

In [ ]:
students={'names':['sarthak','rahul','dev','pragya','varun'],
          'roll_num':[100,200,300,400,500],
          'marks':[30,40,50,60]}
df=pd.DataFrame(students)
#df.index.name='indx'
print(df)

ValueError: All arrays must be of the same length

#create data frame by list

In [ ]:
stud_info=[['sarthak','dev','akansha','pragya'],[10,20,30,40],[100,200,300,400],[20,21,22,23]]
df=pd.DataFrame(stud_info,index=['names','marks','roll_num','age'])
df

                0    1        2       3
names     sarthak  dev  akansha  pragya
marks          10   20       30      40
roll_num      100  200      300     400
age            20   21       22      23

In [ ]:
sr={'name':pd.Series(['sarthak','dev','anurag']),'roll_num':pd.Series([100,200,300])}
df=pd.DataFrame(sr)
df

      name  roll_num
0  sarthak       100
1      dev       200
2   anurag       300

#arithematic in df

In [ ]:
var=pd.DataFrame({'a':[100,101],"b":[200,202],"c":[300,301]})
print(var)

     a    b    c
0  100  200  300
1  101  202  301

In [ ]:
var=pd.DataFrame({'a':[100,101],"b":[200,202],"c":[300,301]})
var["c"]=var["a"]+var["b"]
(var)

     a    b    c
0  100  200  300
1  101  202  303

#filter

In [ ]:
var=pd.DataFrame({'a':[100,101],"b":[200,202],"c":[300,301]})
var["c"]=var["a"]+var["b"]
var['python']=var['b']>200
var

     a    b    c  python
0  100  200  300   False
1  101  202  303    True

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df

      name  roll_num  marks     sub   city
0  sarthak     100.0   10.0    math  delhi
1      NaN       NaN    NaN     sci  delhi
2      dev     200.0   20.0     eng  delhi
3      NaN       NaN    NaN    hist    NaN
4   anurag     300.0  300.0  python    NaN

#handling missing values

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      3 non-null      object
 1   roll_num  3 non-null      float64
 2   marks     3 non-null      float64
 3   sub       5 non-null      object
 4   city      3 non-null      object
dtypes: float64(2), object(3)
memory usage: 332.0+ bytes

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df.isnull()

    name  roll_num  marks    sub   city
0  False     False  False  False  False
1   True      True   True  False  False
2  False     False  False  False  False
3   True      True   True  False   True
4  False     False  False  False   True

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df.isnull().sum()

name        2
roll_num    2
marks       2
sub         0
city        2
dtype: int64

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
print(df.isnull().sum().sum().sum().sum().sum().sum())

8

#remove null value

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df.dropna ()

      name  roll_num  marks   sub   city
0  sarthak     100.0   10.0  math  delhi
2      dev     200.0   20.0   eng  delhi

In [ ]:
#import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df.dropna (subset=['city'])

      name  roll_num  marks   sub   city
0  sarthak     100.0   10.0  math  delhi
1      NaN       NaN    NaN   sci  delhi
2      dev     200.0   20.0   eng  delhi

In [ ]:
#import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df['marks']=df['marks'].fillna("unknown")
df['marks']

0       10.0
1    unknown
2       20.0
3    unknown
4      300.0
Name: marks, dtype: object

In [ ]:
import numpy as np
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df['marks']=df['marks'].fillna(df['marks'].mean())
df['marks']

0     10.0
1    110.0
2     20.0
3    110.0
4    300.0
Name: marks, dtype: float64

In [ ]:
info={"name":["sarthak",np.nan,"dev",np.nan,"anurag"],
      "roll_num":[100,np.nan,200,np.nan,300],
      "marks":[10,np.nan,20,np.nan,300],
      "sub":["math","sci","eng","hist","python"],
      "city":["delhi",'delhi','delhi',np.nan,np.nan]}
df=pd.DataFrame(info)
df['name']=df['name'].fillna('unknown')
df

      name  roll_num  marks     sub   city
0  sarthak     100.0   10.0    math  delhi
1  unknown       NaN    NaN     sci  delhi
2      dev     200.0   20.0     eng  delhi
3  unknown       NaN    NaN    hist    NaN
4   anurag     300.0  300.0  python    NaN

In [ ]:
import pandas as pd

In [ ]:
v1=pd.DataFrame([{"a":[1,2,3],"a":[10,20,30]}])
v2=pd.DataFrame([{"b":[1,2,3],"b":[100,200,300]}])
pd.merge(v1,v2)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [ ]:
v1=pd.DataFrame([{"a":[1,2,3],"a":[10,20,30]}])
v2=pd.DataFrame([{"a":[1,2,3],"a":[100,200,300]}])
pd.merge(v1,v2)

Empty DataFrame
Columns: [a]
Index: []

In [ ]:
v1=pd.DataFrame([{"a":[1,2,3],"b":[10,20,30]}])
v2=pd.DataFrame([{"a":[1,2,3],"c":[100,200,300]}])
pd.merge(v1,v2)

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[10,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,on="rollnum"))
print(m)

   rollnum   name_x name_y
0       10  sarthak      a
1       20      dev      b
2       30   pragya      c

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[10,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,how="left"))
print(m)

   rollnum     name
0       10  sarthak
1       20      dev
2       30   pragya

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[100,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,on="rollnum"))
print(m)

   rollnum  name_x name_y
0       20     dev      b
1       30  pragya      c

In [ ]:
v1=pd.DataFrame({"rollnum":[10000,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[100,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,how="left"))
print(m)

   rollnum     name
0    10000  sarthak
1       20      dev
2       30   pragya

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[10,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,how="right"))
print(m)

   rollnum name
0       10    a
1       20    b
2       30    c

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[1000,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,how="right"))
print(m)

   rollnum name
0     1000    a
1       20    b
2       30    c

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum":[10,20,30],"name":["a","b","c"]})
m=(pd.merge(v1,v2,how="outer",indicator=True))
print(m)

   rollnum     name      _merge
0       10        a  right_only
1       10  sarthak   left_only
2       20        b  right_only
3       20      dev   left_only
4       30        c  right_only
5       30   pragya   left_only

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30,10],"name":["sarthak","dev","pragya","a"]})
v2=pd.DataFrame({"rollnum":[10,20,30,20],"name":["a","b","c","sarthak"]})
m=(pd.merge(v1,v2,how="outer" ))
print(m)

   rollnum     name
0       10        a
1       10  sarthak
2       20        b
3       20      dev
4       20  sarthak
5       30        c
6       30   pragya

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30,10],"name":["sarthak","dev","pragya","a"]})
v2=pd.DataFrame({"rollnum":[10,20,30,20],"name":["a","b","c","sarthak"]})
m=(pd.merge(v1,v2,right_index=True,left_index=True ))
print(m)

   rollnum_x   name_x  rollnum_y   name_y
0         10  sarthak         10        a
1         20      dev         20        b
2         30   pragya         30        c
3         10        a         20  sarthak

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30,10],"name":["sarthak","dev","pragya","a"]})
v2=pd.DataFrame({"rollnum":[10,20,30,20],"name":["a","b","c","sarthak"]})
m=(pd.merge(v1,v2,right_index=True,left_index=True,suffixes=("_9th","_10th") ))
print(m)

   rollnum_9th name_9th  rollnum_10th name_10th
0           10  sarthak            10         a
1           20      dev            20         b
2           30   pragya            30         c
3           10        a            20   sarthak

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30,10],"name":["sarthak","dev","pragya","a"]})
v2=pd.DataFrame({"rollnum":[10,20,30,20],"name":["a","b","c","sarthak"]})
v3=pd.DataFrame({})
m=(pd.merge(v1,v2,right_index=True,left_index=True ))
print(m)

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30,10],"name":["sarthak","dev","pragya","a"]})
v2=pd.DataFrame({"rollnum":[10,20,30,20],"name":["a","b","c","sarthak"]})
m=(pd.merge(v1,v2,right_index=True,left_index=True ))
print(m)

#join

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]})
v2=pd.DataFrame({"rollnum1":[10,20,30],"name1":["a","b","c"]})
v1.join(v2,how="left")

   rollnum     name  rollnum1 name1
0       10  sarthak        10     a
1       20      dev        20     b
2       30   pragya        30     c

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20,30],"name1":["a","b","c"]},index=["a","b","c"])
v1.join(v2,how="left")

   rollnum     name  rollnum1 name1
a       10  sarthak        10     a
b       20      dev        20     b
c       30   pragya        30     c

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v1.join(v2,how="left")

   rollnum     name  rollnum1 name1
a       10  sarthak      10.0     a
b       20      dev      20.0     b
c       30   pragya       NaN   NaN

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v2.join(v1,how="left")

   rollnum1 name1  rollnum     name
a        10     a       10  sarthak
b        20     b       20      dev

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v1.join(v2,how="inner")

   rollnum     name  rollnum1 name1
a       10  sarthak        10     a
b       20      dev        20     b

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v1.join(v2,how="outer")

   rollnum     name  rollnum1 name1
a       10  sarthak      10.0     a
b       20      dev      20.0     b
c       30   pragya       NaN   NaN

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v2.join(v1,how="inner")

   rollnum1 name1  rollnum     name
a        10     a       10  sarthak
b        20     b       20      dev

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v2.join(v1,how="outer")

   rollnum1 name1  rollnum     name
a      10.0     a       10  sarthak
b      20.0     b       20      dev
c       NaN   NaN       30   pragya

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum":[10,20],"name1":["a","b"]},index=["a","b"])
v1.join(v2,how="left",lsuffix="left")

   rollnumleft     name  rollnum name1
a           10  sarthak     10.0     a
b           20      dev     20.0     b
c           30   pragya      NaN   NaN

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v3=pd.DataFrame({"rollnum2":[1,2],"name2":["z","x"]})
v1.join([v2,v3] )

   rollnum     name  rollnum1 name1  rollnum2 name2
a     10.0  sarthak      10.0     a       NaN   NaN
b     20.0      dev      20.0     b       NaN   NaN
c     30.0   pragya       NaN   NaN       NaN   NaN

In [ ]:
v1=pd.DataFrame({"rollnum":[10,20,30],"name":["sarthak","dev","pragya"]},index=["a","b","c"])
v2=pd.DataFrame({"rollnum1":[10,20],"name1":["a","b"]},index=["a","b"])
v3=pd.DataFrame({"rollnum2":[1,2],"name2":["z","x"]})
v1.join(v2).join(v3)

   rollnum     name  rollnum1 name1  rollnum2 name2
a       10  sarthak      10.0     a       NaN   NaN
b       20      dev      20.0     b       NaN   NaN
c       30   pragya       NaN   NaN       NaN   NaN